# Generated by Django 3.2.9 on 2021-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_profile_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
